serviceAccount: projects/brave-inn-477912-q1/serviceAccounts/cloud-build-sa@brave-inn-477912-q1.iam.gserviceaccount.com
logsBucket: gs://vault-cloudbuild-bucket

options:
  pool:
    name: projects/brave-inn-477912-q1/locations/us-central1/workerPools/vault-cloudbuild-pool

steps:
  # 0) Test connectivity and get credentials
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    id: "test-gke-connectivity"
    entrypoint: bash
    args:
      - -lc
      - |
        set -euxo pipefail

        # Get credentials using the INTERNAL IP (essential for Private Pools)
        gcloud container clusters get-credentials gke-vault \
          --region us-central1 \
          --project brave-inn-477912-q1 \
          --internal-ip

        # Fixed: --short is deprecated and causes errors in newer kubectl versions
        kubectl version --client
        
        # Test the connection
        kubectl get nodes -o wide

  # 1) Terraform Apply
  - name: hashicorp/terraform:1.9
    id: "terraform-helm-layer"
    entrypoint: sh
    args:
      - -c
      - |
        set -eu

        
        terraform -chdir=cloudbuild/infra-cloudbuild init -input=false
        terraform -chdir=cloudbuild/infra-cloudbuild plan -input=false -out=tfplan
        terraform -chdir=cloudbuild/infra-cloudbuild apply -input=false -auto-approve tfplan